/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vcc.ui;

import com.vcc.form.workspace.VPGWorkspaceForm;

/**
 *
 * @author david
 */
public class WorkspacePanel extends javax.swing.JPanel {

    final private VPGWorkspaceForm workspaceForm;
    
    public String getWorkspaceName() {
        return workspaceForm.getName();
    }
    
    /**
     * Creates new form PanelWorkspace
     * @param workspaceForm
     */
    public WorkspacePanel(VPGWorkspaceForm workspaceForm) {
        initComponents();
        
        this.workspaceForm = workspaceForm;
    }
    
    public long getTabOrder() {
        return workspaceForm.getTabOrder();
    }
    
    public void close(boolean isForce) {
        workspaceForm.close(isForce);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spBase = new javax.swing.JSplitPane();
        spLeft = new javax.swing.JScrollPane();
        trWorkspace = new javax.swing.JTree();
        pnlBase = new javax.swing.JPanel();

        spBase.setDividerSize(2);

        spLeft.setViewportView(trWorkspace);

        spBase.setLeftComponent(spLeft);

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        spBase.setRightComponent(pnlBase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spBase, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spBase, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlBase;
    private javax.swing.JSplitPane spBase;
    private javax.swing.JScrollPane spLeft;
    private javax.swing.JTree trWorkspace;
    // End of variables declaration//GEN-END:variables
}
