package com.vcc;

import com.vcc.ui.WorkspacePanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author david
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public Main() {
        initComponents();
        
        setTitle("VCC Project Manager");
        WorkspacePanel panel = new WorkspacePanel();
        tpWorkspace.addTab("Default", panel);
//        // initialize interface
//        spBase.setDividerLocation(100);
//        spMain.setDividerLocation(spMain.getSize().height - 100);
//        //setIconImage(new ImageIcon(getClass().getResource("/resources/abc.png")).getImage());
//    
//        VPGMainForm form = new VPGMainForm();
//        form.doAddWorkspaceForm();
//        System.out.println(form.getWorkspaceFormsCount());
//        form.removeWorkspaceForms(form.getWorkspaceFormsAtIndex(0));
//        System.out.println(form.getWorkspaceFormsCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpWorkspace = new javax.swing.JTabbedPane();
        mbMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        mbMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        mbMenuBar.add(jMenu2);

        setJMenuBar(mbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpWorkspace, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpWorkspace, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } 
        catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // Set the property to use the screen menu bar on macOS
        System.setProperty("apple.laf.useScreenMenuBar", "true");
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar mbMenuBar;
    private javax.swing.JTabbedPane tpWorkspace;
    // End of variables declaration//GEN-END:variables
}
