package com.vcc;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.PointerByReference;

public interface VPGDllFunctions extends Library {
    VPGDllFunctions Instance = loadLibrary();

    static private VPGDllFunctions loadLibrary() {
        String prefix = System.getProperty("os.name").startsWith("Windows") ? "lib" : "";
        var lib = (VPGDllFunctions)Native.load(prefix + "vpg", VPGDllFunctions.class);
        lib.ApplicationStart();
        return lib;
    }

    int GetVersion(PointerByReference str);
    Pointer CreateObject(long objectType);
    long ApplicationClearFormAction(Pointer form);
    boolean ApplicationCloseForm(Pointer form, boolean isForce);
    Pointer ApplicationCreateForm(long formType);
    void ApplicationDoFormAction(Pointer form, long formProperty);
    long ApplicationGetFormActionFirstSeqNo(Pointer form);
    long ApplicationGetFormActionLastSeqNo(Pointer form);
    boolean ApplicationIsFormClosable(Pointer form);
    boolean ApplicationIsFormClosed(Pointer form);
    long ApplicationRedoFormAction(Pointer form, long noOfStep);
    long ApplicationRedoFormActionToSeqNo(Pointer form, long seqNo);
    void ApplicationStart();
    long ApplicationTruncateFormAction(Pointer form);
    long ApplicationUndoFormAction(Pointer form, long noOfStep);
    long ApplicationUndoFormActionToSeqNo(Pointer form, long seqNo);
    boolean ReadBool(Pointer ref, long property);
    boolean ReadBoolAtIndex(Pointer ref, long property, long index);
    boolean ReadBoolAtKey(Pointer ref, long property, Pointer key);
    void WriteBool(Pointer ref, long property, boolean value);
    void WriteBoolAtIndex(Pointer ref, long property, boolean value, long index);
    void WriteBoolAtKey(Pointer ref, long property, boolean value, Pointer key);
    void InsertBoolAtIndex(Pointer ref, long property, boolean value, long index);
    byte ReadChar(Pointer ref, long property);
    byte ReadCharAtIndex(Pointer ref, long property, long index);
    byte ReadCharAtKey(Pointer ref, long property, Pointer key);
    void WriteChar(Pointer ref, long property, byte value);
    void WriteCharAtIndex(Pointer ref, long property, byte value, long index);
    void WriteCharAtKey(Pointer ref, long property, byte value, Pointer key);
    void InsertCharAtIndex(Pointer ref, long property, byte value, long index);
    char ReadWchar(Pointer ref, long property);
    char ReadWcharAtIndex(Pointer ref, long property, long index);
    char ReadWcharAtKey(Pointer ref, long property, Pointer key);
    void WriteWchar(Pointer ref, long property, char value);
    void WriteWcharAtIndex(Pointer ref, long property, char value, long index);
    void WriteWcharAtKey(Pointer ref, long property, char value, Pointer key);
    void InsertWcharAtIndex(Pointer ref, long property, char value, long index);
    int ReadInt8(Pointer ref, long property);
    int ReadInt8AtIndex(Pointer ref, long property, long index);
    int ReadInt8AtKey(Pointer ref, long property, Pointer key);
    void WriteInt8(Pointer ref, long property, int value);
    void WriteInt8AtIndex(Pointer ref, long property, int value, long index);
    void WriteInt8AtKey(Pointer ref, long property, int value, Pointer key);
    void InsertInt8AtIndex(Pointer ref, long property, int value, long index);
    int ReadUint8(Pointer ref, long property);
    int ReadUint8AtIndex(Pointer ref, long property, long index);
    int ReadUint8AtKey(Pointer ref, long property, Pointer key);
    void WriteUint8(Pointer ref, long property, int value);
    void WriteUint8AtIndex(Pointer ref, long property, int value, long index);
    void WriteUint8AtKey(Pointer ref, long property, int value, Pointer key);
    void InsertUint8AtIndex(Pointer ref, long property, int value, long index);
    int ReadShort(Pointer ref, long property);
    int ReadShortAtIndex(Pointer ref, long property, long index);
    int ReadShortAtKey(Pointer ref, long property, Pointer key);
    void WriteShort(Pointer ref, long property, int value);
    void WriteShortAtIndex(Pointer ref, long property, int value, long index);
    void WriteShortAtKey(Pointer ref, long property, int value, Pointer key);
    void InsertShortAtIndex(Pointer ref, long property, int value, long index);
    int ReadUnsignedShort(Pointer ref, long property);
    int ReadUnsignedShortAtIndex(Pointer ref, long property, long index);
    int ReadUnsignedShortAtKey(Pointer ref, long property, Pointer key);
    void WriteUnsignedShort(Pointer ref, long property, int value);
    void WriteUnsignedShortAtIndex(Pointer ref, long property, int value, long index);
    void WriteUnsignedShortAtKey(Pointer ref, long property, int value, Pointer key);
    void InsertUnsignedShortAtIndex(Pointer ref, long property, int value, long index);
    long ReadInt(Pointer ref, long property);
    long ReadIntAtIndex(Pointer ref, long property, long index);
    long ReadIntAtKey(Pointer ref, long property, Pointer key);
    void WriteInt(Pointer ref, long property, long value);
    void WriteIntAtIndex(Pointer ref, long property, long value, long index);
    void WriteIntAtKey(Pointer ref, long property, long value, Pointer key);
    void InsertIntAtIndex(Pointer ref, long property, long value, long index);
    long ReadUnsignedInt(Pointer ref, long property);
    long ReadUnsignedIntAtIndex(Pointer ref, long property, long index);
    long ReadUnsignedIntAtKey(Pointer ref, long property, Pointer key);
    void WriteUnsignedInt(Pointer ref, long property, long value);
    void WriteUnsignedIntAtIndex(Pointer ref, long property, long value, long index);
    void WriteUnsignedIntAtKey(Pointer ref, long property, long value, Pointer key);
    void InsertUnsignedIntAtIndex(Pointer ref, long property, long value, long index);
    long ReadLong(Pointer ref, long property);
    long ReadLongAtIndex(Pointer ref, long property, long index);
    long ReadLongAtKey(Pointer ref, long property, Pointer key);
    void WriteLong(Pointer ref, long property, long value);
    void WriteLongAtIndex(Pointer ref, long property, long value, long index);
    void WriteLongAtKey(Pointer ref, long property, long value, Pointer key);
    void InsertLongAtIndex(Pointer ref, long property, long value, long index);
    long ReadUnsignedLong(Pointer ref, long property);
    long ReadUnsignedLongAtIndex(Pointer ref, long property, long index);
    long ReadUnsignedLongAtKey(Pointer ref, long property, Pointer key);
    void WriteUnsignedLong(Pointer ref, long property, long value);
    void WriteUnsignedLongAtIndex(Pointer ref, long property, long value, long index);
    void WriteUnsignedLongAtKey(Pointer ref, long property, long value, Pointer key);
    void InsertUnsignedLongAtIndex(Pointer ref, long property, long value, long index);
    float ReadFloat(Pointer ref, long property);
    float ReadFloatAtIndex(Pointer ref, long property, long index);
    float ReadFloatAtKey(Pointer ref, long property, Pointer key);
    void WriteFloat(Pointer ref, long property, float value);
    void WriteFloatAtIndex(Pointer ref, long property, float value, long index);
    void WriteFloatAtKey(Pointer ref, long property, float value, Pointer key);
    void InsertFloatAtIndex(Pointer ref, long property, float value, long index);
    double ReadDouble(Pointer ref, long property);
    double ReadDoubleAtIndex(Pointer ref, long property, long index);
    double ReadDoubleAtKey(Pointer ref, long property, Pointer key);
    void WriteDouble(Pointer ref, long property, double value);
    void WriteDoubleAtIndex(Pointer ref, long property, double value, long index);
    void WriteDoubleAtKey(Pointer ref, long property, double value, Pointer key);
    void InsertDoubleAtIndex(Pointer ref, long property, double value, long index);
    void ReadString(Pointer ref, long property, PointerByReference value);
    void ReadStringAtIndex(Pointer ref, long property, PointerByReference value, long index);
    void ReadStringAtKey(Pointer ref, long property, PointerByReference value, Pointer key);
    void WriteString(Pointer ref, long property, PointerByReference value);
    void WriteStringAtIndex(Pointer ref, long property, PointerByReference value, long index);
    void WriteStringAtKey(Pointer ref, long property, PointerByReference value, Pointer key);
    void InsertStringAtIndex(Pointer ref, long property, PointerByReference value, long index);
    Pointer ReadObject(Pointer ref, long property);
    Pointer ReadObjectAtIndex(Pointer ref, long property, long index);
    Pointer ReadObjectAtKey(Pointer ref, long property, Pointer key);
    void WriteObject(Pointer ref, long property, Pointer value);
    void WriteObjectAtIndex(Pointer ref, long property, Pointer value, long index);
    void WriteObjectAtKey(Pointer ref, long property, Pointer value, Pointer key);
    Pointer AddObjectAtIndex(Pointer ref, long property, long objectType, long index);
    void InsertObjectAtIndex(Pointer ref, long property, Pointer value, long index);
    long GetCount(Pointer ref, long property);
    Pointer GetMapKeys(Pointer ref, long property);
    boolean IsContainKey(Pointer ref, long property, Pointer key);
    void RemoveObject(Pointer ref, long property, Pointer value);
    void RemoveAtIndex(Pointer ref, long property, long index);
    void RemoveAtKey(Pointer ref, long property, Pointer key);
    void Clear(Pointer ref, long property);
}
