package com.vcc;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.PointerByReference;

public interface VPGDllFunctions extends Library {
    VPGDllFunctions Instance = loadLibrary();

    static private VPGDllFunctions loadLibrary() {
        String prefix = System.getProperty("os.name").startsWith("Windows") ? "lib" : "";
        return (VPGDllFunctions)Native.load(prefix + "vpg", VPGDllFunctions.class);
    }

    int GetVersion(PointerByReference str);
    Pointer CreateObject(long objectType);
    boolean ReadBool(Pointer ref, long property, long index);
    boolean ReadBoolByKey(Pointer ref, long property, Pointer key);
    void WriteBool(Pointer ref, long property, boolean value, long index);
    void WriteBoolByKey(Pointer ref, long property, boolean value, Pointer key);
    void InsertBool(Pointer ref, long property, boolean value, long index);
    byte ReadChar(Pointer ref, long property, long index);
    byte ReadCharByKey(Pointer ref, long property, Pointer key);
    void WriteChar(Pointer ref, long property, byte value, long index);
    void WriteCharByKey(Pointer ref, long property, byte value, Pointer key);
    void InsertChar(Pointer ref, long property, byte value, long index);
    char ReadWchar(Pointer ref, long property, long index);
    char ReadWcharByKey(Pointer ref, long property, Pointer key);
    void WriteWchar(Pointer ref, long property, char value, long index);
    void WriteWcharByKey(Pointer ref, long property, char value, Pointer key);
    void InsertWchar(Pointer ref, long property, char value, long index);
    int ReadInt8(Pointer ref, long property, long index);
    int ReadInt8ByKey(Pointer ref, long property, Pointer key);
    void WriteInt8(Pointer ref, long property, int value, long index);
    void WriteInt8ByKey(Pointer ref, long property, int value, Pointer key);
    void InsertInt8(Pointer ref, long property, int value, long index);
    int ReadUint8(Pointer ref, long property, long index);
    int ReadUint8ByKey(Pointer ref, long property, Pointer key);
    void WriteUint8(Pointer ref, long property, int value, long index);
    void WriteUint8ByKey(Pointer ref, long property, int value, Pointer key);
    void InsertUint8(Pointer ref, long property, int value, long index);
    int ReadShort(Pointer ref, long property, long index);
    int ReadShortByKey(Pointer ref, long property, Pointer key);
    void WriteShort(Pointer ref, long property, int value, long index);
    void WriteShortByKey(Pointer ref, long property, int value, Pointer key);
    void InsertShort(Pointer ref, long property, int value, long index);
    int ReadUnsignedShort(Pointer ref, long property, long index);
    int ReadUnsignedShortByKey(Pointer ref, long property, Pointer key);
    void WriteUnsignedShort(Pointer ref, long property, int value, long index);
    void WriteUnsignedShortByKey(Pointer ref, long property, int value, Pointer key);
    void InsertUnsignedShort(Pointer ref, long property, int value, long index);
    long ReadInt(Pointer ref, long property, long index);
    long ReadIntByKey(Pointer ref, long property, Pointer key);
    void WriteInt(Pointer ref, long property, long value, long index);
    void WriteIntByKey(Pointer ref, long property, long value, Pointer key);
    void InsertInt(Pointer ref, long property, long value, long index);
    long ReadUnsignedInt(Pointer ref, long property, long index);
    long ReadUnsignedIntByKey(Pointer ref, long property, Pointer key);
    void WriteUnsignedInt(Pointer ref, long property, long value, long index);
    void WriteUnsignedIntByKey(Pointer ref, long property, long value, Pointer key);
    void InsertUnsignedInt(Pointer ref, long property, long value, long index);
    long ReadLong(Pointer ref, long property, long index);
    long ReadLongByKey(Pointer ref, long property, Pointer key);
    void WriteLong(Pointer ref, long property, long value, long index);
    void WriteLongByKey(Pointer ref, long property, long value, Pointer key);
    void InsertLong(Pointer ref, long property, long value, long index);
    long ReadUnsignedLong(Pointer ref, long property, long index);
    long ReadUnsignedLongByKey(Pointer ref, long property, Pointer key);
    void WriteUnsignedLong(Pointer ref, long property, long value, long index);
    void WriteUnsignedLongByKey(Pointer ref, long property, long value, Pointer key);
    void InsertUnsignedLong(Pointer ref, long property, long value, long index);
    float ReadFloat(Pointer ref, long property, long index);
    float ReadFloatByKey(Pointer ref, long property, Pointer key);
    void WriteFloat(Pointer ref, long property, float value, long index);
    void WriteFloatByKey(Pointer ref, long property, float value, Pointer key);
    void InsertFloat(Pointer ref, long property, float value, long index);
    double ReadDouble(Pointer ref, long property, long index);
    double ReadDoubleByKey(Pointer ref, long property, Pointer key);
    void WriteDouble(Pointer ref, long property, double value, long index);
    void WriteDoubleByKey(Pointer ref, long property, double value, Pointer key);
    void InsertDouble(Pointer ref, long property, double value, long index);
    void ReadString(Pointer ref, long property, PointerByReference value, long index);
    void ReadStringByKey(Pointer ref, long property, PointerByReference value, Pointer key);
    void WriteString(Pointer ref, long property, PointerByReference value, long index);
    void WriteStringByKey(Pointer ref, long property, PointerByReference value, Pointer key);
    void InsertString(Pointer ref, long property, PointerByReference value, long index);
    Pointer ReadObject(Pointer ref, long property, long index);
    Pointer ReadObjectByKey(Pointer ref, long property, Pointer key);
    void WriteObject(Pointer ref, long property, Pointer value, long index);
    void WriteObjectByKey(Pointer ref, long property, Pointer value, Pointer key);
    Pointer AddObject(Pointer ref, long property, long objectType, long index);
    void InsertObject(Pointer ref, long property, Pointer value, long index);
    long GetContainerCount(Pointer ref, long property);
    Pointer GetMapKeys(Pointer ref, long property);
    boolean IsContainKey(Pointer ref, long property, Pointer key);
    void RemoveContainerElement(Pointer ref, long property, long index);
    void RemoveContainerElementByKey(Pointer ref, long property, Pointer key);
    void ClearContainer(Pointer ref, long property);
}
