package com.vcc;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.PointerByReference;

public interface VPGDllFunctions extends Library {
    VPGDllFunctions Instance = loadLibrary();

    static private VPGDllFunctions loadLibrary() {
        String prefix = System.getProperty("os.name").startsWith("Windows") ? "lib" : "";
        var lib = (VPGDllFunctions)Native.load(prefix + "vpg", VPGDllFunctions.class);
        lib.applicationStart();
        return lib;
    }

    int getVersion(PointerByReference str);
    long applicationClearFormAction(Pointer form);
    boolean applicationCloseForm(Pointer form, boolean isForce);
    Pointer applicationCreateActionArgument(long objectType);
    Pointer applicationCreateForm(long objectType);
    Pointer applicationDoFormAction(Pointer form, long formProperty, Pointer argument);
    void applicationEraseResult(Pointer result);
    long applicationGetFormActionCurrentSeqNo(Pointer form);
    long applicationGetFormActionFirstSeqNo(Pointer form);
    long applicationGetFormActionLastSeqNo(Pointer form);
    long applicationGetResultErrorCode(Pointer result);
    void applicationGetResultMessage(Pointer result, PointerByReference value);
    boolean applicationIsErrorResult(Pointer result);
    boolean applicationIsFormClosable(Pointer form);
    boolean applicationIsFormClosed(Pointer form);
    boolean applicationIsWarningResult(Pointer result);
    void applicationRedoFormAction(Pointer form, long noOfStep);
    void applicationRedoFormActionToSeqNo(Pointer form, long seqNo);
    void applicationStart();
    long applicationTruncateFormAction(Pointer form);
    void applicationUndoFormAction(Pointer form, long noOfStep);
    void applicationUndoFormActionToSeqNo(Pointer form, long seqNo);
    boolean readBool(Pointer ref, long property);
    boolean readBoolAtIndex(Pointer ref, long property, long index);
    boolean readBoolAtKey(Pointer ref, long property, Pointer key);
    void writeBool(Pointer ref, long property, boolean value);
    void writeBoolAtIndex(Pointer ref, long property, boolean value, long index);
    void writeBoolAtKey(Pointer ref, long property, boolean value, Pointer key);
    void insertBoolAtIndex(Pointer ref, long property, boolean value, long index);
    byte readChar(Pointer ref, long property);
    byte readCharAtIndex(Pointer ref, long property, long index);
    byte readCharAtKey(Pointer ref, long property, Pointer key);
    void writeChar(Pointer ref, long property, byte value);
    void writeCharAtIndex(Pointer ref, long property, byte value, long index);
    void writeCharAtKey(Pointer ref, long property, byte value, Pointer key);
    void insertCharAtIndex(Pointer ref, long property, byte value, long index);
    char readWchar(Pointer ref, long property);
    char readWcharAtIndex(Pointer ref, long property, long index);
    char readWcharAtKey(Pointer ref, long property, Pointer key);
    void writeWchar(Pointer ref, long property, char value);
    void writeWcharAtIndex(Pointer ref, long property, char value, long index);
    void writeWcharAtKey(Pointer ref, long property, char value, Pointer key);
    void insertWcharAtIndex(Pointer ref, long property, char value, long index);
    int readInt8(Pointer ref, long property);
    int readInt8AtIndex(Pointer ref, long property, long index);
    int readInt8AtKey(Pointer ref, long property, Pointer key);
    void writeInt8(Pointer ref, long property, int value);
    void writeInt8AtIndex(Pointer ref, long property, int value, long index);
    void writeInt8AtKey(Pointer ref, long property, int value, Pointer key);
    void insertInt8AtIndex(Pointer ref, long property, int value, long index);
    int readUint8(Pointer ref, long property);
    int readUint8AtIndex(Pointer ref, long property, long index);
    int readUint8AtKey(Pointer ref, long property, Pointer key);
    void writeUint8(Pointer ref, long property, int value);
    void writeUint8AtIndex(Pointer ref, long property, int value, long index);
    void writeUint8AtKey(Pointer ref, long property, int value, Pointer key);
    void insertUint8AtIndex(Pointer ref, long property, int value, long index);
    int readShort(Pointer ref, long property);
    int readShortAtIndex(Pointer ref, long property, long index);
    int readShortAtKey(Pointer ref, long property, Pointer key);
    void writeShort(Pointer ref, long property, int value);
    void writeShortAtIndex(Pointer ref, long property, int value, long index);
    void writeShortAtKey(Pointer ref, long property, int value, Pointer key);
    void insertShortAtIndex(Pointer ref, long property, int value, long index);
    int readUnsignedShort(Pointer ref, long property);
    int readUnsignedShortAtIndex(Pointer ref, long property, long index);
    int readUnsignedShortAtKey(Pointer ref, long property, Pointer key);
    void writeUnsignedShort(Pointer ref, long property, int value);
    void writeUnsignedShortAtIndex(Pointer ref, long property, int value, long index);
    void writeUnsignedShortAtKey(Pointer ref, long property, int value, Pointer key);
    void insertUnsignedShortAtIndex(Pointer ref, long property, int value, long index);
    long readInt(Pointer ref, long property);
    long readIntAtIndex(Pointer ref, long property, long index);
    long readIntAtKey(Pointer ref, long property, Pointer key);
    void writeInt(Pointer ref, long property, long value);
    void writeIntAtIndex(Pointer ref, long property, long value, long index);
    void writeIntAtKey(Pointer ref, long property, long value, Pointer key);
    void insertIntAtIndex(Pointer ref, long property, long value, long index);
    long readUnsignedInt(Pointer ref, long property);
    long readUnsignedIntAtIndex(Pointer ref, long property, long index);
    long readUnsignedIntAtKey(Pointer ref, long property, Pointer key);
    void writeUnsignedInt(Pointer ref, long property, long value);
    void writeUnsignedIntAtIndex(Pointer ref, long property, long value, long index);
    void writeUnsignedIntAtKey(Pointer ref, long property, long value, Pointer key);
    void insertUnsignedIntAtIndex(Pointer ref, long property, long value, long index);
    long readLong(Pointer ref, long property);
    long readLongAtIndex(Pointer ref, long property, long index);
    long readLongAtKey(Pointer ref, long property, Pointer key);
    void writeLong(Pointer ref, long property, long value);
    void writeLongAtIndex(Pointer ref, long property, long value, long index);
    void writeLongAtKey(Pointer ref, long property, long value, Pointer key);
    void insertLongAtIndex(Pointer ref, long property, long value, long index);
    long readUnsignedLong(Pointer ref, long property);
    long readUnsignedLongAtIndex(Pointer ref, long property, long index);
    long readUnsignedLongAtKey(Pointer ref, long property, Pointer key);
    void writeUnsignedLong(Pointer ref, long property, long value);
    void writeUnsignedLongAtIndex(Pointer ref, long property, long value, long index);
    void writeUnsignedLongAtKey(Pointer ref, long property, long value, Pointer key);
    void insertUnsignedLongAtIndex(Pointer ref, long property, long value, long index);
    float readFloat(Pointer ref, long property);
    float readFloatAtIndex(Pointer ref, long property, long index);
    float readFloatAtKey(Pointer ref, long property, Pointer key);
    void writeFloat(Pointer ref, long property, float value);
    void writeFloatAtIndex(Pointer ref, long property, float value, long index);
    void writeFloatAtKey(Pointer ref, long property, float value, Pointer key);
    void insertFloatAtIndex(Pointer ref, long property, float value, long index);
    double readDouble(Pointer ref, long property);
    double readDoubleAtIndex(Pointer ref, long property, long index);
    double readDoubleAtKey(Pointer ref, long property, Pointer key);
    void writeDouble(Pointer ref, long property, double value);
    void writeDoubleAtIndex(Pointer ref, long property, double value, long index);
    void writeDoubleAtKey(Pointer ref, long property, double value, Pointer key);
    void insertDoubleAtIndex(Pointer ref, long property, double value, long index);
    void readString(Pointer ref, long property, PointerByReference value);
    void readStringAtIndex(Pointer ref, long property, PointerByReference value, long index);
    void readStringAtKey(Pointer ref, long property, PointerByReference value, Pointer key);
    void writeString(Pointer ref, long property, PointerByReference value);
    void writeStringAtIndex(Pointer ref, long property, PointerByReference value, long index);
    void writeStringAtKey(Pointer ref, long property, PointerByReference value, Pointer key);
    void insertStringAtIndex(Pointer ref, long property, PointerByReference value, long index);
    Pointer readObject(Pointer ref, long property);
    Pointer readObjectAtIndex(Pointer ref, long property, long index);
    Pointer readObjectAtKey(Pointer ref, long property, Pointer key);
    void writeObject(Pointer ref, long property, Pointer value);
    void writeObjectAtIndex(Pointer ref, long property, Pointer value, long index);
    void writeObjectAtKey(Pointer ref, long property, Pointer value, Pointer key);
    Pointer addObjectAtIndex(Pointer ref, long property, long objectType, long index);
    void insertObjectAtIndex(Pointer ref, long property, Pointer value, long index);
    long getCount(Pointer ref, long property);
    Pointer getMapKeys(Pointer ref, long property);
    boolean isContainKey(Pointer ref, long property, Pointer key);
    void removeObject(Pointer ref, long property, Pointer value);
    void removeAtIndex(Pointer ref, long property, long index);
    void removeAtKey(Pointer ref, long property, Pointer key);
    void clear(Pointer ref, long property);
}
